output_strategy: "kafka"
csv_file_path: "data/parking.csv"

file:
  output_file: "data/output.json"

redis:
  host: "localhost"
  port: 6379

kafka:
  bootstrap_servers: "localhost:9092"
  topic: "shootings"